name: Linux Release

on:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

  steps:
    - uses: actions/checkout@v6

    - name: Install deps
      run: |
        sudo apt-get update 
        sudo apt install -y libpcap-dev libwayland-dev

    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - uses: actions/upload-artifact@v7
      with:
        name: reliquary-archiver-linux-pcap-x64
        path: target/release/reliquary-archiver
