name: Linux Release

on:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Install deps
        run: |
          sudo apt-get update 
          sudo apt install -y libpcap-dev libwayland-dev

      - name: Build
        run: cargo build --release

      - name: Create directories
        run: |
          mkdir -p AppDir/usr/bin \
          AppDir/usr/lib \
          AppDir/usr/share/icons/hicolor/256x256/apps \
          AppDir/usr/share/applications \

      - name: Create AppRun script and desktop file
        run: |
          echo '#!/bin/sh
          HERE="$(dirname "$(readlink -f "$0")")"
          APPIMAGE_LIB_DIRS="$HERE/usr/lib:$HERE/usr/lib/x86_64-linux-gnu"
          export LD_LIBRARY_PATH="$APPIMAGE_LIB_DIRS:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib"
          exec "$HERE/usr/bin/reliquary-archiver" "$@"' > AppDir/AppRun 
          chmod +x AppDir/AppRun

          echo -e '[Desktop Entry]\nType=Application\nName=reliquary-archiver\nExec=reliquary-archiver\nIcon=reliquary-archiver\Categories=Utility;\nTerminal=true' > AppDir/usr/share/applications/reliquary-archiver.desktop
          chmod +x AppDir/usr/share/applications/reliquary-archiver.desktop

      - name: copy files
        run: |
          cp target/release/reliquary-archiver AppDir/usr/bin/ 
          chmod +x AppDir/usr/bin/reliquary-archiver
          LIBPCAP_PATH=$(ldconfig -p | grep "libpcap.so" | awk '{print $NF}' | head -n 1)
          cp "$LIBPCAP_PATH" AppDir/usr/lib/
          cp assets/icon256.png AppDir/usr/share/icons/hicolor/256x256/apps/reliquary-archiver.png
          cp AppDir/usr/share/icons/hicolor/256x256/apps/reliquary-archiver.png AppDir/reliquary-archiver.png
          cp AppDir/usr/share/applications/reliquary-archiver.desktop AppDir/reliquary-archiver.desktop

      - name: check files
        run: |
          ls -lah AppDir/ AppDir/usr/ AppDir/usr/bin/ AppDir/usr/lib/
          cat AppDir/AppRun
          cat AppDir/reliquary-archiver.desktop

      - name: Download appimagetool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
          chmod +x appimagetool

      - name: Pack AppImage
        run: |
          ./appimagetool --appimage-extract
          ./squashfs-root/AppRun AppDir reliquary.AppImage

      - uses: actions/upload-artifact@v7
        with:
          name: reliquary-archiver-x86_64.AppImage
          path: reliquary.AppImage
